app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/amigoscode
      username: sa
      password: 'bhu8BHU*'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always


